formatter: "markdown" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  show:
    - providers
    - inputs
    - outputs

content: |-
  {{ .Header }}

  ## Overview
  Linux virtual machine module. 

  Simplifies creating a Linux virtual machine by requiring only two parameters: resource group and subnet id.  Module expects admin user's public SSH key to be in ```~/.ssh/id_rsa.pub``` or a specified via ```admin_ssh_public_key_path```.  Alternatively,  ```disable_password_authentication``` can be set to ```false``` and ```admin_password``` to the desired admin password.  Default VM image is a Red Hat one, or an alternate one can be specified via ```urn``` and if needed, ```plan``` .
 
  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}  


output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: false

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
