formatter: "markdown" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  show:
    - providers
    - inputs
    - outputs
    - resources
    - modules

content: |-
  {{ .Header }}

  ## Overview
  On-premises network simulator module. 

  - Intended to integrate with  [hub](../hub/README.md) and [s2svpn-winra-vpng](../s2svpn-winra-vpng/README.md) modules.
  - Creates and deploys its resources to the resource group ```onprem-rg```. 
  - Top-level [README](../README.md) explains the resources in detail and how they fit into a [larger architecture](../images/hub-spoke.png).
  - ```winra_vm_admin_password``` is the only required input parameter.

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}  

  {{ .Resources }}

  {{ .Modules }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: false

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: false
  sensitive: true
  type: false
