formatter: "markdown" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  show:
    - providers
    - inputs
    - outputs

content: |-
  {{ .Header }}

  ## Overview
  Linux virtual machine module. 

  Simplifies creating a Linux virtual machine by requiring only several input parameters: ```resource_group_name``` and ```snet_id``` (subnet id).  Module expects admin user's public SSH key to be on host where Terraform is running, either in ```~/.ssh/id_rsa.pub``` (default) or a specified via ```admin_ssh_public_key_path```.  Alternatively,  ```disable_password_authentication``` can be set to ```false``` and ```admin_password``` to the desired admin password.  VM image is Red Hat (default) and can be changed via ```urn``` and ```plan```.
 
  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}  

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: false

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
