formatter: "markdown" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  show:
    - providers
    - inputs
    - outputs

content: |-
  {{ .Header }}

  ## Overview
  Windows virtual machine module. 

  Simplifies creating a Windows virtual machine by requiring only several input parameters: ```resource_group_name```, ```snet_id``` (subnet id), and ```admin_password```.  Default VM image is Windows Server. An alternate can be specified via ```urn``` and when needed, ```plan``` .
 
  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}  


output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: false

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
